# Generated by Django 5.2.14 on 2026-05-23 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année académique')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('verrouillee', 'Verrouillée')], default='ouverte', max_length=12, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('etudiant', models.ForeignKey(limit_choices_to={'profile__role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('etudiant', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='ModuleChoisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_choisis', to='inscription.inscription', verbose_name='Inscription')),
                ('module_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_etudiants', to='catalogue.cataloguemodule', verbose_name='Module du catalogue')),
            ],
            options={
                'verbose_name': 'Module choisi',
                'verbose_name_plural': 'Modules choisis',
                'unique_together': {('inscription', 'module_catalogue')},
            },
        ),
    ]
