# Generated by Django 5.2.14 on 2026-05-23 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulechoisi',
            name='module_catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choix_etudiants', to='catalogue.cataloguemodule', verbose_name='Module du catalogue'),
        ),
    ]
