# Generated by Django 5.2.14 on 2026-05-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Note entre 0 et 20', max_digits=4, verbose_name='Note')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('categorie_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='catalogue.categorieevaluation', verbose_name="Catégorie d'évaluation")),
                ('module_choisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inscription.modulechoisi', verbose_name='Module choisi')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['date_saisie'],
                'unique_together': {('module_choisi', 'categorie_evaluation')},
            },
        ),
    ]
