# Generated by Django 5.2.14 on 2026-05-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200, unique=True, verbose_name='Intitulé')),
                ('coefficient', models.PositiveIntegerField(verbose_name='Coefficient')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Module du catalogue',
                'verbose_name_plural': 'Modules du catalogue',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='CategorieEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('poids', models.PositiveIntegerField(verbose_name='Poids (%)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_evaluation', to='catalogue.cataloguemodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': "Catégorie d'évaluation",
                'verbose_name_plural': "Catégories d'évaluation",
                'ordering': ['module', 'nom'],
                'unique_together': {('nom', 'module')},
            },
        ),
    ]
